#   This file contains the tunable build parameters for the library, allowing
#    for simple specification at build-time to override the default values
#    specified in the library itself.

#   This variable holds the full set of additional definitions to pass to the compiler.
TUNING_PARAMETERS :=

VERBOSE_TEST_SUCCESS :=
LIBCONTAINER_ZERO_ON_RELEASE := 1
LIBCONTAINER_ARRAY_DEFAULT_CAPACITY :=
LIBCONTAINER_HASHMAP_LOAD_FACTOR :=
LIBCONTAINER_HASHMAP_DEFAULT_CAPACITY :=

ifdef VERBOSE_TEST_SUCCESS
TUNING_PARAMETERS += -DVERBOSE_TEST_SUCCESS
endif

ifdef LIBCONTAINER_ZERO_ON_RELEASE
TUNING_PARAMETERS += -DLIBCONTAINER_ZERO_ON_RELEASE
endif

ifdef LIBCONTAINER_ARRAY_DEFAULT_CAPACITY
TUNING_PARAMETERS += -DLIBCONTAINER_ARRAY_DEFAULT_CAPACITY=$(LIBCONTAINER_ARRAY_DEFAULT_CAPACITY)
endif

ifdef LIBCONTAINER_HASHMAP_LOAD_FACTOR
TUNING_PARAMETERS += -DLIBCONTAINER_HASHMAP_LOAD_FACTOR=$(LIBCONTAINER_HASHMAP_LOAD_FACTOR)
endif

ifdef LIBCONTAINER_HASHMAP_DEFAULT_CAPACITY
TUNING_PARAMETERS += -DLIBCONTAINER_HASHMAP_DEFAULT_CAPACITY=$(LIBCONTAINER_HASHMAP_DEFAULT_CAPACITY)
endif

#	Add in the version and build-time info macros
TUNING_PARAMETERS += -DLIBCONTAINER_MAJOR_VERSION=$(MAJOR_VERSION)
TUNING_PARAMETERS += -DLIBCONTAINER_MINOR_VERSION=$(MINOR_VERSION)
TUNING_PARAMETERS += -DLIBCONTAINER_PATCH_VERSION=$(PATCH_VERSION)
TUNING_PARAMETERS += -DLIBCONTAINER_BUILD_DATE="\"$(BUILD_DATE)\""
TUNING_PARAMETERS += -DLIBCONTAINER_BUILD_DATESTAMP=$(BUILD_DATESTAMP)

#   Add up all of the additional definitions to the basic set of compiler flags.
CFLAGS += $(TUNING_PARAMETERS)
